### ISSUE TITLE
Result too bright if video have black bar

### ISSUE THREAD

**Issue by kedaitinh12** [Asd-g/AviSynth-Retinex#1]
If we will cut the black bar, result had been work perfect but i think it's still bug. Can you fix retinex work well when don't need cut black bar??
https://forum.doom9.org/showthread.php?p=1952303#post1952303

**Comment by Asd-g** [comment]
This is not a bug. The behavior is similar to GIMP Retinex (level "high").

If you don't want to filter an image with black bars crop them and after add them back.

**Comment by kedaitinh12** [comment]
Ok, thanks
