### ISSUE TITLE
32 bit float

### ISSUE THREAD

**Issue by DonCanjas** [Asd-g/AviSynth-Retinex#2]
Would it be possible to add 32 bit float support?

**Comment by Asd-g** [comment]
I will take a look.

**Comment by Asd-g** [comment]
You can try the latest version.

**Comment by DonCanjas** [comment]
Thank you.

At 32 bit, the output looks surprisingly different with the same sigma. Is it expected behaviour?


```
DGSource("DBK - 035.dgi")
Crop(242, 0, -242, 0)

#ConvertBits(16)
ConvertBits(32)

Retinex_MSRCP(sigma=[25, 80, 250])
```

16 bit
<img src=https://user-images.githubusercontent.com/80267631/179806511-f4d85636-d8f8-4a37-a074-bfc2fbadfea6.png width="300" />

32 bit
<img src=https://user-images.githubusercontent.com/80267631/179806531-9f59ef3c-2a3a-4806-9171-fadb6971dd04.png width="300" />

**Comment by dnjulek** [comment]
The difference is that "auto gain" is only applied when not full, and float input is considered full by default. 
The ideal would be to apply it even when float.

https://github.com/Asd-g/AviSynth-Retinex/blob/54081a4b4191dddb2edf8a5752bd30d9c6504148/src/Retinex.cpp#L1029

**Comment by Asd-g** [comment]
`fulls` and `fulld` are always true when the clip is 32-bit. The correct comparison is:

32-bit:
```
ConvertBits(32, fulls=false, fulld=true)
MSRCP(sigma=[25, 80, 250])
```
16-bit:
```
ConvertBits(16, fulls=false, fulld=true)
MSRCP(sigma=[25, 80, 250], fulls=true)
```

**Comment by DonCanjas** [comment]
> `fulls` and `fulld` are always true when the clip is 32-bit. The correct comparison is:
> 
> 32-bit:
> 
> ```
> ConvertBits(32, fulls=false, fulld=true)
> MSRCP(sigma=[25, 80, 250])
> ```
> 
> 16-bit:
> 
> ```
> ConvertBits(16, fulls=false, fulld=true)
> MSRCP(sigma=[25, 80, 250], fulls=true)
> ```

Alright, like that it's working properly.
